name: Flutter Profile Build


on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.4'
          channel: 'stable'
          cache: true

      - name: Install dependencies
        run: |
          flutter pub get
          
      - name: Build exe
        run: flutter build windows --release --no-tree-shake-icons

      - name: Check dependencies
        run: |
          ls

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: release-deobfercator-dev-exe
          path: build\windows\x64\runner\Release\deobfercator.exe


  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: release-deobfercator-exe

      - name: Check dependencies
        run: |
          ls

      # Releasing the build
      - name: Releasing build
        uses: ncipollo/release-action@v1
        with:
          artifacts: "app-release.apk"
          tag: v1.0.${{ github.run_number }}