name: Flutter Profile Build


on:
  push:
    branches:
      - master

permissions:
  contents: write
jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.4'
          channel: 'stable'
          cache: true

      - name: Install dependencies
        run: |
          flutter pub get
          
      - name: Build exe
        run: flutter build windows --release --no-tree-shake-icons

      - name: Check dependencies
        run: |
          ls

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: release-deobfercator-exe
          path: build\windows\x64\runner\Release\deobfercator.exe

  build-macos:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.4'
          channel: 'stable'
          cache: true

      - name: Install dependencies
        run: |
          flutter pub get
          
      - name: Build exe
        run: flutter build macos --release --no-tree-shake-icons

      - name: Check dependencies
        run: |
          ls

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: release-deobfercator-app
          path: build/macos/Build/Products/Release/deobfercator.app

  release:
    runs-on: windows-latest
    needs:
      - build-macos
      - build
    steps:
      - name: Download macOS Artifact
        uses: actions/download-artifact@v4
        with:
          name: release-deobfercator-app
          path: artifacts/macos

      - name: Download Windows Artifact
        uses: actions/download-artifact@v4
        with:
          name: release-deobfercator-exe
          path: artifacts/windows

      - name: Check dependencies
        run: |
          ls
          cd artifacts/macos
          ls
          

      # Releasing the build
      - name: Releasing build
        uses: ncipollo/release-action@v1
        with:
          artifacts: "artifacts/macos/deobfercator.app, artifacts/windows/deobfercator.exe"
          tag: v1.0.${{ github.run_number }}